# -*- coding: utf-8 -*-
"""Punto_10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

##**Punto 10**
"""

import numpy
from numpy import arctan

def AproxArctan(x: float, n:int) -> float:
  suma: float = 0
  for i in range(-2, 2):
    y = ((-1)**i)*(((x**((2*i)+1))/((2*i)+1)))
    suma += y
  return suma

if __name__ == "__main__":
  x = float(input("Ingrese un número real: "))
  n: int = 1
  aprox: float = AproxArctan(x, n)
  valorReal: float = arctan(x)

  while ((abs(valorReal - aprox)/valorReal * 100)<0.1):
    aprox: float = AproxArctan(x, n)
    n += 1
  print("El valor de n para tener un error menor a 0.1: " + str(n))

  print("La aproximación es: " + str(aprox))
  print("El valor real es: " + str(valorReal))