# -*- coding: utf-8 -*-
"""Punto_9

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

##**Punto 9**
"""

import math
from math import sin, factorial

def AproxSeno(x: float, n:int) -> float:
  suma: float = 0
  for i in range(0, n+1):
    y = ((-1)**i)*((x**((2*i)+1))/factorial((2*i)+1))
    suma += y
  return suma

if __name__ == "__main__":
  x = float(input("Ingrese un número real: "))
  n: int = 1
  aprox: float = AproxSeno(x, n)
  valorReal: float = sin(x)

  while ((abs(valorReal - aprox)/valorReal * 100)>0.1):
    aprox: float = AproxSeno(x, n)
    n += 1
  print("El valor de n para tener un error menor a 0.1: " + str(n))

  print("La aproximación es: " + str(aprox))
  print("El valor real es: " + str(valorReal))