# -*- coding: utf-8 -*-
"""Punto_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

# **Cuarto Punto**

**Enunciado:** Imprimir los números de 1 hasta un número natural n dado, cada uno con su respectivo factorial
"""

import math as m
n = int(input("Ingrese un número natural: "))
factorial = 0

for i in range(1, n+1, +1):
  factorial = m.factorial(i)
  print("El factorial de " + str(i) + " es: " + str(factorial))